modLoader="javafml"
loaderVersion="[31,)"
license="MIT"

[[mods]]
modId="potioncakes"
version="0.1"
displayName="Potion Cakes"
issueTrackerURL=""
displayURL=""
logoFile=""
credits=""
authors="AreUThreateningMe"
description='''
Potion Cakes
'''
[[dependencies.potioncakes]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.potioncakes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="AFTER"
    side="BOTH"
